export const dynamic = 'force-dynamic'
import { notFound } from 'next/navigation'
import { createServiceClient } from '@/lib/supabase/service'
import { freshnessFor, daysUntilExpiry } from '@/lib/ledger/credentials/types'

const FRESH_STYLE: Record<string, { bg: string; color: string; label: string }> = {
  active: { bg: 'var(--sage-50)', color: 'var(--sage)', label: 'ACTIVE' },
  expiring_soon: { bg: 'var(--gold-50)', color: 'var(--ink)', label: 'EXPIRING SOON' },
  expired: { bg: 'var(--tang-50)', color: 'var(--tang-mid)', label: 'EXPIRED' },
  unknown: { bg: 'var(--g100)', color: 'var(--g600)', label: 'NO EXPIRY' },
}

export default async function PublicCredentialSharePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const supabase = createServiceClient()

  const { data: link } = await supabase
    .rpc('increment_credential_share_view', { p_slug: slug })
    .maybeSingle() as { data: { id: string; credential_id: string; expose_document: boolean } | null }

  if (!link) notFound()

  const { data: credential } = await supabase
    .from('credentials')
    .select('id, type, display_name, issuer, card_number, issued_at, expires_at, status, document_url')
    .eq('id', link.credential_id)
    .single()

  if (!credential) notFound()

  const fresh = freshnessFor(credential.expires_at)
  const days = daysUntilExpiry(credential.expires_at)
  const s = FRESH_STYLE[fresh]

  return (
    <div className="flex flex-col min-h-screen" style={{ background: 'var(--cream)' }}>
      <header className="border-b" style={{ borderColor: 'var(--g100)', background: 'white' }}>
        <div className="max-w-[800px] mx-auto px-4 py-5">
          <div className="text-[11px] font-bold tracking-wider" style={{ color: 'var(--tang)' }}>NURSESQUARE · CREDENTIAL VERIFICATION</div>
          <h1 className="font-display text-2xl mt-1" style={{ color: 'var(--ink)' }}>{credential.display_name ?? credential.type}</h1>
        </div>
      </header>
      <main className="max-w-[800px] mx-auto w-full px-4 py-10">
        <div className="rounded-2xl border p-6" style={{ borderColor: 'var(--g100)', background: 'white' }}>
          <div className="flex items-center justify-between mb-6">
            <div>
              <div className="text-[11px] font-bold tracking-wider" style={{ color: 'var(--g400)' }}>TYPE</div>
              <div className="text-sm font-mono mt-1" style={{ color: 'var(--ink)' }}>{credential.type}</div>
            </div>
            <span className="text-[11px] font-bold tracking-wider px-3 py-1.5 rounded" style={{ background: s.bg, color: s.color }}>
              {s.label}
            </span>
          </div>
          <dl className="grid grid-cols-2 gap-x-6 gap-y-4 text-sm">
            <Item label="Issuer" value={credential.issuer ?? '—'} />
            <Item label="Card / certificate #" value={credential.card_number ?? '—'} />
            <Item label="Issued" value={credential.issued_at ?? '—'} />
            <Item label="Expires" value={credential.expires_at ? `${credential.expires_at}${days !== null ? ` (${days >= 0 ? days : Math.abs(days)} days ${days >= 0 ? 'remaining' : 'ago'})` : ''}` : '—'} />
            <Item label="Status" value={credential.status} />
          </dl>
          {link.expose_document && credential.document_url && (
            <a href={credential.document_url} target="_blank" rel="noreferrer"
              className="inline-block mt-6 px-4 py-2 rounded-lg font-bold text-sm text-white no-underline" style={{ background: 'var(--plum)' }}>
              View original document
            </a>
          )}
        </div>
        <p className="text-xs mt-6" style={{ color: 'var(--g600)' }}>
          This page is a verification link generated by the credential owner via NurseSquare. The owner controls expiration and whether the original document is visible. Source of truth is the issuing body.
        </p>
      </main>
    </div>
  )
}

function Item({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-[11px] font-bold tracking-wider" style={{ color: 'var(--g400)' }}>{label.toUpperCase()}</dt>
      <dd className="text-sm mt-1" style={{ color: 'var(--ink)' }}>{value}</dd>
    </div>
  )
}
