import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PDFDocument from 'pdfkit'

export async function POST(req: NextRequest) {
  const { jobId } = await req.json()
  if (!jobId) return NextResponse.json({ error: 'Missing jobId' }, { status: 400 })

  const supabase = await createClient()

  const { data: checklist } = await supabase
    .from('onboarding_checklists')
    .select('*, job_postings(title, city, state, start_date, specialty_required, employer_profiles(org_name, address, city, state, zip))')
    .eq('job_id', jobId)
    .single()

  if (!checklist) return NextResponse.json({ error: 'Checklist not found' }, { status: 404 })

  const job = checklist.job_postings
  const employer = job?.employer_profiles

  const doc = new PDFDocument({ margin: 50 })
  const chunks: Buffer[] = []

  doc.on('data', chunk => chunks.push(chunk))

  await new Promise<void>(resolve => {
    doc.on('end', resolve)

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('NurseSquare Onboarding Packet', { align: 'center' })
    doc.moveDown(0.5)
    doc.fontSize(14).font('Helvetica').text(job?.title || 'Placement', { align: 'center' })
    doc.fontSize(12).fillColor('#555').text(employer?.org_name || '', { align: 'center' })
    doc.moveDown()

    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2563eb').moveDown()

    // Job details
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#1e3a5f').text('Job Details')
    doc.moveDown(0.3)
    const details = [
      ['Facility', employer?.org_name],
      ['Location', `${job?.city}, ${job?.state}`],
      ['Specialty', job?.specialty_required],
      ['Start Date', job?.start_date ? new Date(job.start_date).toLocaleDateString('en-US', { dateStyle: 'long' }) : 'TBD'],
      ['Address', `${employer?.address}, ${employer?.city}, ${employer?.state} ${employer?.zip}`],
    ]
    doc.fontSize(11).font('Helvetica').fillColor('#333')
    details.forEach(([label, value]) => {
      doc.text(`${label}: `, { continued: true }).font('Helvetica-Bold').text(value || 'N/A').font('Helvetica')
    })

    doc.moveDown()
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e5e7eb').moveDown()

    // Checklist sections
    const sections = [
      { title: 'Parking Instructions', content: checklist.parking },
      { title: 'Who to Report To', content: checklist.report_to },
      { title: 'Dress Code', content: checklist.dress_code },
      { title: 'Unit Protocols & Systems', content: checklist.unit_protocols },
      { title: 'Badge Pickup', content: checklist.badge_pickup },
    ]

    if (checklist.additional_notes) {
      sections.push({ title: 'Additional Notes', content: checklist.additional_notes })
    }

    sections.forEach(section => {
      if (section.content) {
        doc.fontSize(13).font('Helvetica-Bold').fillColor('#1e3a5f').text(section.title)
        doc.moveDown(0.2)
        doc.fontSize(11).font('Helvetica').fillColor('#333').text(section.content, { lineGap: 3 })
        doc.moveDown()
      }
    })

    // Footer
    doc.fontSize(9).fillColor('#888').text(
      `Generated by NurseSquare · ${new Date().toLocaleDateString()} · nursesquare.com`,
      { align: 'center' }
    )

    doc.end()
  })

  const pdfBuffer = Buffer.concat(chunks)

  const fileName = `onboarding/${jobId}.pdf`
  const { error: uploadError } = await supabase.storage
    .from('documents')
    .upload(fileName, pdfBuffer, {
      contentType: 'application/pdf',
      upsert: true,
    })

  if (!uploadError) {
    const { data: urlData } = supabase.storage.from('documents').getPublicUrl(fileName)
    await supabase
      .from('onboarding_checklists')
      .update({ pdf_url: urlData.publicUrl })
      .eq('job_id', jobId)
  }

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="onboarding-${jobId}.pdf"`,
    },
  })
}
